kind: pipeline
name: Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison cpio
      - git config --global user.name "AtomicXZ"
      - git config --global user.email "achubadyal4@gmail.com"
      - git config --global color.ui false
      - mkdir Nb && cd Nb
      - wget https://raw.githubusercontent.com/AtomicXZ/android_kernel_xiaomi_phoenix/rn/build.sh
      - bash build.sh
